export const ActionTypes = {
    ADD_TO_BASKET : "ADD_TO_BASKET",
    REMOVE_FROM_BASKET : "REMOVE_FROM_BASKET",
    RESET_PRODUCTS : "RESET_PRODUCTS",
    LOGIN_SET: "LOGIN_SET",
    SIGN_OUT: "SIGNOUT"
}